---
title: "dtw_oecd_gap_report"
author: "Kefan Yu"
date: "2023-10-25"
output: html_document
---

```{r}
library(readxl)
library(dtwclust)
library(dtw)
```

```{r}
reading <- read_excel("../../data/oecd/oecd_gender_clean.xlsx", sheet = "Reading")
math <- read_excel("../../data/oecd/oecd_gender_clean.xlsx", sheet = "Math")
sci <- read_excel("../../data/oecd/oecd_gender_clean.xlsx", sheet = "Science")
```

Reading

```{r}
reading <- subset(reading, select = -c(...1) )
country = reading[['Countries']]
dtw_reading <- reading[, -1]
```

```{r}
reading_lst <- tslist(dtw_reading)

remove_nan <- function(ts) {
  ts[!is.na(ts)]
}

# Apply the function to each time series in the list
reading_lst <- lapply(reading_lst, remove_nan)
```

```{r}
reading_cvi <- list()
for (i in 2:10){
  reading_clust <- tsclust(reading_lst, type = "partitional", k = i, distance = "dtw", centroid = "pam",set.seed(5))
  reading_metric <- cvi(reading_clust, type = "valid", log.base = 10)
  reading_cvi <- append(reading_cvi, list(reading_metric))
}

reading_cvi_ma <- do.call(rbind, reading_cvi)
rw <- c("K2","K3","K4","K5","K6","K7","K8","K9","K10")
rownames(reading_cvi_ma) <- rw
print(reading_cvi_ma)
```

```{r}
reading_clust_opt <- tsclust(reading_lst, type = "partitional", k = 4, distance = "dtw", centroid = "pam",seed = 725)
plot(reading_clust_opt)
```

```{r}
print(t(cbind(reading$Countries, cluster = reading_clust_opt@cluster)))
```

```{r}
result_reading_avg = cbind(reading$Countries, cluster = reading_clust_opt@cluster)
result_reading_avg <- as.data.frame(result_reading_avg)

cat("Number of countries in K1: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "4", ]), "\n")
```

cluster 1 only has Chile, Colombia, Mexico

```{r}
reading_clust_opt_h <- tsclust(reading_lst, type = "h", k = 4, distance = "dtw", seed = 725)
plot(reading_clust_opt_h, type="sc")
```

```{r}
print(t(cbind(reading$Countries, cluster = reading_clust_opt_h@cluster)))
```

```{r}
result_reading_avg_h = cbind(reading$Countries, cluster = reading_clust_opt_h@cluster)
result_reading_avg_h <- as.data.frame(result_reading_avg_h)

cat("Number of countries in K1: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "4", ]), "\n")
```

cluster 4 only has Isreal

Math

```{r}
math <- subset(math, select = -c(...1) )
sci <- subset(sci, select = -c(...1) )
```

```{r}
dtw_math <- math[, -1]

math_lst <- tslist(dtw_math)

# Apply the function to each time series in the list
math_lst <- lapply(math_lst, remove_nan)
```

```{r}
math_cvi <- list()
for (i in 2:10){
  math_clust <- tsclust(math_lst, type = "partitional", k = i, distance = "dtw", centroid = "pam",set.seed(4))
  math_metric <- cvi(math_clust, type = "valid", log.base = 10)
  math_cvi <- append(math_cvi, list(math_metric))
}

math_cvi_ma <- do.call(rbind, math_cvi)
rownames(math_cvi_ma) <- rw
print(math_cvi_ma)
```

```{r}
math_clust_opt <- tsclust(math_lst, type = "partitional", k = 3, distance = "dtw", centroid = "pam",seed = 725)
plot(math_clust_opt)
```

```{r}
print(t(cbind(math$Countries, cluster = math_clust_opt@cluster)))
```

```{r}
result_math_avg = cbind(reading$Countries, cluster = math_clust_opt@cluster)
result_math_avg <- as.data.frame(result_math_avg)

cat("Number of countries in K1: ", nrow(result_math_avg[result_math_avg['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_math_avg[result_math_avg['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_math_avg[result_math_avg['cluster'] == "3", ]), "\n")
```

```{r}
math_clust_opt_h <- tsclust(math_lst, type = "h", k = 3, distance = "dtw", seed = 725)
plot(math_clust_opt_h, type="sc")
```

```{r}
print(t(cbind(reading$Countries, cluster = math_clust_opt_h@cluster)))
```

It is interesting to see that Korea is clustered with Colombia and Chile together

```{r}
result_math_avg_h = cbind(reading$Countries, cluster = math_clust_opt_h@cluster)
result_math_avg_h <- as.data.frame(result_math_avg_h)

cat("Number of countries in K1: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "3", ]), "\n")
```

Science

```{r}
dtw_sci <- sci[, -1]

sci_lst <- tslist(dtw_sci)

# Apply the function to each time series in the list
sci_lst <- lapply(sci_lst, remove_nan)

```

```{r}
sci_cvi <- list()
for (i in 2:10){
  sci_clust <- tsclust(sci_lst, type = "partitional", k = i, distance = "dtw", centroid = "pam",set.seed(4))
  sci_metric <- cvi(sci_clust, type = "valid", log.base = 10)
  sci_cvi <- append(sci_cvi, list(sci_metric))
}

sci_cvi_ma <- do.call(rbind, sci_cvi)
rownames(sci_cvi_ma) <- rw
print(sci_cvi_ma)
```

```{r}
sci_clust_opt <- tsclust(sci_lst, type = "partitional", k = 3, distance = "dtw", centroid = "pam",seed = 725)
plot(sci_clust_opt)
```

```{r}
print(t(cbind(sci$Countries, cluster = sci_clust_opt@cluster)))
```

```{r}
result_sci_avg = cbind(reading$Countries, cluster = sci_clust_opt@cluster)
result_sci_avg <- as.data.frame(result_sci_avg)

cat("Number of countries in K1: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "3", ]), "\n")
```

```{r}
sci_clust_opt_h <- tsclust(sci_lst, type = "h", k = 3, distance = "dtw", seed = 725)
plot(sci_clust_opt_h, type="sc")
```

```{r}
print(t(cbind(reading$Countries, cluster = sci_clust_opt_h@cluster)))
```

```{r}
result_sci_avg_h = cbind(reading$Countries, cluster = sci_clust_opt_h@cluster)
result_sci_avg_h <- as.data.frame(result_sci_avg_h)

cat("Number of countries in K1: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "3", ]), "\n")
```