---
title: "dtw_oecd_rank_filled"
author: "Kefan Yu"
date: "2023-10-29"
output: html_document
---

```{r}
library(readxl)
library(dtwclust)
library(dtw)
```

```{r}
reading <- read_excel("../../data/oecd/oecd_rank.xlsx", sheet = "Reading")
math <- read_excel("../../data/oecd/oecd_rank.xlsx", sheet = "Math")
sci <- read_excel("../../data/oecd/oecd_rank.xlsx", sheet = "Science")
```


```{r}
reading <- subset(reading, select = -c(...1) )
math <- subset(math, select = -c(...1) )
sci <- subset(sci, select = -c(...1) )
country = reading[['Countries']]
```

```{r}
reading_missing <- list(year2000 = c(),
                year2003 = c(),
                year2006 = c(),
                year2009 = c(),
                year2012 = c(),
                year2015 = c(),
                year2018 = c())

reading_nan <- which(is.na(reading$`2000`) | is.na(reading$`2003`) | is.na(reading$`2006`) | is.na(reading$`2009`) | is.na(reading$`2012`) | is.na(reading$`2015`) | is.na(reading$`2018`))

for (reading_index in reading_nan) {
  
  if (is.na(reading$`2000`[reading_index])){
    reading_missing$year2000 <- append(reading_missing$year2000, reading$Countries[reading_index])
  }
  if (is.na(reading$`2003`[reading_index])){
    reading_missing$year2003 <- append(reading_missing$year2003, reading$Countries[reading_index])
  }
  if (is.na(reading$`2006`[reading_index])){
    reading_missing$year2006 <- append(reading_missing$year2006, reading$Countries[reading_index])
  }
  if (is.na(reading$`2009`[reading_index])){
    reading_missing$year2009 <- append(reading_missing$year2009, reading$Countries[reading_index])
  }
  if (is.na(reading$`2012`[reading_index])){
    reading_missing$year2012 <- append(reading_missing$year2012, reading$Countries[reading_index])
  }
  if (is.na(reading$`2015`[reading_index])){
    reading_missing$year2015 <- append(reading_missing$year2015, reading$Countries[reading_index])
  }
  if (is.na(reading$`2018`[reading_index])){
    reading_missing$year2018 <- append(reading_missing$year2018, reading$Countries[reading_index])
  }
    #cat("Countries: ",reading$Countries[reading_index], "\n")
  
}
```

```{r}
print(reading_missing)
```

```{r}
math_missing <- list(year2000 = c(),
                year2003 = c(),
                year2006 = c(),
                year2009 = c(),
                year2012 = c(),
                year2015 = c(),
                year2018 = c())

math_nan <- which(is.na(math$`2000`) | is.na(math$`2003`) | is.na(math$`2006`) | is.na(math$`2009`) | is.na(math$`2012`) | is.na(math$`2015`) | is.na(math$`2018`))

for (math_index in math_nan) {
  
  if (is.na(math$`2000`[math_index])){
    math_missing$year2000 <- append(math_missing$year2000, math$Countries[math_index])
  }
  if (is.na(math$`2003`[math_index])){
    math_missing$year2003 <- append(math_missing$year2003, math$Countries[math_index])
  }
  if (is.na(math$`2006`[math_index])){
    math_missing$year2006 <- append(math_missing$year2006, math$Countries[math_index])
  }
  if (is.na(math$`2009`[math_index])){
    math_missing$year2009 <- append(math_missing$year2009, math$Countries[math_index])
  }
  if (is.na(math$`2012`[math_index])){
    math_missing$year2012 <- append(math_missing$year2012, math$Countries[math_index])
  }
  if (is.na(math$`2015`[math_index])){
    math_missing$year2015 <- append(math_missing$year2015, math$Countries[math_index])
  }
  if (is.na(math$`2018`[math_index])){
    math_missing$year2018 <- append(math_missing$year2018, math$Countries[math_index])
  }
    #cat("Countries: ",reading$Countries[reading_index], "\n")
  
}
```

```{r}
print(math_missing)
```

```{r}
sci_missing <- list(year2000 = c(),
                year2003 = c(),
                year2006 = c(),
                year2009 = c(),
                year2012 = c(),
                year2015 = c(),
                year2018 = c())

sci_nan <- which(is.na(sci$`2000`) | is.na(sci$`2003`) | is.na(sci$`2006`) | is.na(sci$`2009`) | is.na(sci$`2012`) | is.na(sci$`2015`) | is.na(sci$`2018`))

for (sci_index in sci_nan) {
  
  if (is.na(sci$`2000`[sci_index])){
    sci_missing$year2000 <- append(sci_missing$year2000, sci$Countries[sci_index])
  }
  if (is.na(sci$`2003`[sci_index])){
    sci_missing$year2003 <- append(sci_missing$year2003, sci$Countries[sci_index])
  }
  if (is.na(sci$`2006`[sci_index])){
    sci_missing$year2006 <- append(sci_missing$year2006, sci$Countries[sci_index])
  }
  if (is.na(sci$`2009`[sci_index])){
    sci_missing$year2009 <- append(sci_missing$year2009, sci$Countries[sci_index])
  }
  if (is.na(sci$`2012`[sci_index])){
    sci_missing$year2012 <- append(sci_missing$year2012, sci$Countries[sci_index])
  }
  if (is.na(sci$`2015`[sci_index])){
    sci_missing$year2015 <- append(sci_missing$year2015, sci$Countries[sci_index])
  }
  if (is.na(sci$`2018`[sci_index])){
    sci_missing$year2018 <- append(sci_missing$year2018, sci$Countries[sci_index])
  }
    #cat("Countries: ",reading$Countries[reading_index], "\n")
  
}
```

```{r}
print(sci_missing)
```
```{r}
library(zoo)
```

```{r}
dtw_reading <- reading[, -1]
dtw_reading[] <- t(apply(dtw_reading, 1, function(x) na.locf0(na.locf0(x), fromLast = TRUE)))
reading_lst <- tslist(dtw_reading)

reading_cvi <- list()
for (i in 2:10){
  reading_clust <- tsclust(reading_lst, type = "partitional", k = i, distance = "dtw", centroid = "pam",set.seed(5))
  reading_metric <- cvi(reading_clust, type = "valid", log.base = 10)
  reading_cvi <- append(reading_cvi, list(reading_metric))
}

reading_cvi_ma <- do.call(rbind, reading_cvi)
rw <- c("K2","K3","K4","K5","K6","K7","K8","K9","K10")
rownames(reading_cvi_ma) <- rw
print(reading_cvi_ma)

```

```{r}
reading_clust_opt <- tsclust(reading_lst, type = "partitional", k = 4, distance = "dtw", centroid = "pam",seed = 725)
plot(reading_clust_opt)
```

```{r}
print(t(cbind(reading$Countries, cluster = reading_clust_opt@cluster)))
```

```{r}
result_reading_avg = cbind(reading$Countries, cluster = reading_clust_opt@cluster)
result_reading_avg <- as.data.frame(result_reading_avg)

cat("Number of countries in K1: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_reading_avg[result_reading_avg['cluster'] == "4", ]), "\n")
```

```{r}
reading_clust_opt_h <- tsclust(reading_lst, type = "h", k = 4, distance = "dtw", seed = 725)
plot(reading_clust_opt_h, type="sc")
```

```{r}
print(t(cbind(reading$Countries, cluster = reading_clust_opt_h@cluster)))
```

```{r}
result_reading_avg_h = cbind(reading$Countries, cluster = reading_clust_opt_h@cluster)
result_reading_avg_h <- as.data.frame(result_reading_avg_h)

cat("Number of countries in K1: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_reading_avg_h[result_reading_avg_h['cluster'] == "4", ]), "\n")
```

```{r}
dtw_math <- math[, -1]

dtw_math <- subset(dtw_math, select = -c(`2000`) )

dtw_math[] <- t(apply(dtw_math, 1, function(x) na.locf0(na.locf0(x), fromLast = TRUE)))

math_lst <- tslist(dtw_math)
```

```{r}
math_cvi <- list()
for (i in 2:10){
  math_clust <- tsclust(math_lst, type = "partitional", k = i, distance = "dtw", centroid = "pam",set.seed(4))
  math_metric <- cvi(math_clust, type = "valid", log.base = 10)
  math_cvi <- append(math_cvi, list(math_metric))
}

math_cvi_ma <- do.call(rbind, math_cvi)
rownames(math_cvi_ma) <- rw
print(math_cvi_ma)
```

```{r}
math_clust_opt6 <- tsclust(math_lst, type = "partitional", k = 6, distance = "dtw", centroid = "pam",seed = 725)
plot(math_clust_opt6)
```

```{r}
print(t(cbind(math$Countries, cluster = math_clust_opt6@cluster)))
```

```{r}
result_math_rank = cbind(reading$Countries, cluster = math_clust_opt6@cluster)
result_math_rank <- as.data.frame(result_math_rank)

cat("Number of countries in K1: ", nrow(result_math_rank[result_math_rank['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_math_rank[result_math_rank['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_math_rank[result_math_rank['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_math_rank[result_math_rank['cluster'] == "4", ]), "\n")
cat("Number of countries in K5: ", nrow(result_math_rank[result_math_rank['cluster'] == "5", ]), "\n")
cat("Number of countries in K6: ", nrow(result_math_rank[result_math_rank['cluster'] == "6", ]), "\n")
```

```{r}
math_clust_opt_h <- tsclust(math_lst, type = "h", k = 6, distance = "dtw", seed = 725)
plot(math_clust_opt_h, type="sc")
```

```{r}
print(t(cbind(reading$Countries, cluster = math_clust_opt_h@cluster)))
```

```{r}
result_math_avg_h = cbind(reading$Countries, cluster = math_clust_opt_h@cluster)
result_math_avg_h <- as.data.frame(result_math_avg_h)

cat("Number of countries in K1: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "4", ]), "\n")
cat("Number of countries in K5: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "5", ]), "\n")
cat("Number of countries in K6: ", nrow(result_math_avg_h[result_math_avg_h['cluster'] == "6", ]), "\n")
```

```{r}
dtw_sci <- sci[, -1]
dtw_sci <- subset(dtw_sci, select = -c(`2000`,`2003`) )
dtw_sci[] <- t(apply(dtw_sci, 1, function(x) na.locf0(na.locf0(x), fromLast = TRUE)))
sci_lst <- tslist(dtw_sci)


sci_cvi <- list()
for (i in 2:10){
  sci_clust <- tsclust(sci_lst, type = "partitional", k = i, distance = "dtw", centroid = "pam",set.seed(4))
  sci_metric <- cvi(sci_clust, type = "valid", log.base = 10)
  sci_cvi <- append(sci_cvi, list(sci_metric))
}

sci_cvi_ma <- do.call(rbind, sci_cvi)
rownames(sci_cvi_ma) <- rw
print(sci_cvi_ma)

```

```{r}
sci_clust_opt <- tsclust(sci_lst, type = "partitional", k = 4, distance = "dtw", centroid = "pam",seed = 725)
plot(sci_clust_opt)
```

```{r}
print(t(cbind(sci$Countries, cluster = sci_clust_opt@cluster)))
```

```{r}
result_sci_avg = cbind(reading$Countries, cluster = sci_clust_opt@cluster)
result_sci_avg <- as.data.frame(result_sci_avg)

cat("Number of countries in K1: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_sci_avg[result_sci_avg['cluster'] == "4", ]), "\n")
```

```{r}
sci_clust_opt_h <- tsclust(sci_lst, type = "h", k = 4, distance = "dtw", seed = 725)
plot(sci_clust_opt_h, type="sc")
```

```{r}
print(t(cbind(reading$Countries, cluster = sci_clust_opt_h@cluster)))
```

```{r}
result_sci_avg_h = cbind(reading$Countries, cluster = sci_clust_opt_h@cluster)
result_sci_avg_h <- as.data.frame(result_sci_avg_h)

cat("Number of countries in K1: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "1", ]), "\n")
cat("Number of countries in K2: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "2", ]), "\n")
cat("Number of countries in K3: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "3", ]), "\n")
cat("Number of countries in K4: ", nrow(result_sci_avg_h[result_sci_avg_h['cluster'] == "4", ]), "\n")
```